### ISSUE TITLE
[Bug]: Hey, Not working when @stencil/core is ^3.0.0 version

### ISSUE THREAD

**Issue by ayangweb** [saasquatch/stencil-hooks#11]
I copied the case of [live-demo](https://studio.webcomponents.dev/edit/gqVMwvd4PFqN3isJPt2h) in the ^3.0.0 version of the component, but the following happened, I hope to solve the problem, thanks!

<img width="1757" alt="iShot_2023-07-08_22 15 38" src="https://github.com/saasquatch/stencil-hooks/assets/75017711/fe176333-14ed-4152-a5c1-a6f4d137f390">

**Comment by 00salmon** [comment]
A PR has been opened that should resolve this issue. [#12](https://github.com/saasquatch/stencil-hooks/pull/12).

**Comment by 00salmon** [comment]
A PR has been opened that should resolve this issue. [#12](https://github.com/saasquatch/stencil-hooks/pull/12).

**Comment by ayangweb** [comment]
> A PR has been opened that should resolve this issue. [#12](https://github.com/saasquatch/stencil-hooks/pull/12).

OK, it's really great!

**Comment by 00salmon** [comment]
Fixed in https://github.com/saasquatch/stencil-hooks/pull/12
`@saasquatch/stencil-hooks@3.0.0`

**Comment by ayangweb** [comment]
> Fixed in #12 `@saasquatch/stencil-hooks@3.0.0`

After testing, it doesn't work when packaged as other packages like `vue`, `react`, etc!
